### PR TITLE
Redesign login page

### PR DESCRIPTION
**Pull request by maxailloud**
I propose to you a redesign of the login page.
Of course it's just a proposition that needs approval before being merged.
See the new page with the facebook connection button:

login-page

And without the facebook connection button:
login-page-facebook

A PR for the FacebookBundle is on its way for a little redesign of the button.

### CODE REVIEW

**Comment by ngodfraind** [comment]
I like it.

2015-05-21 14:13 GMT+02:00 Maxime AILLOUD <notifications@github.com>:

> I propose to you a redesign of the login page.
> Of course it's just a proposition that needs approval before being merged.
> See the new page with the facebook connection button:
>
> [image: login-page]
> <https://cloud.githubusercontent.com/assets/792787/7748284/5cc7a4ce-ffc3-11e4-9db2-a34210853e90.png>
>
> And without the facebook connection button:
> [image: login-page-facebook]
> <https://cloud.githubusercontent.com/assets/792787/7748285/611e130a-ffc3-11e4-9282-cefcb0cdb57e.png>
>
> A PR for the FacebookBundle is on its way for a little redesign of the
> button.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/claroline/CoreBundle/pull/1206
> Commit Summary
>
>    - Redesign login page
>
> File Changes
>
>    - *M* Controller/AuthenticationController.php
>    <https://github.com/claroline/CoreBundle/pull/1206/files#diff-0> (7)
>    - *M* Resources/views/Authentication/login.html.twig
>    <https://github.com/claroline/CoreBundle/pull/1206/files#diff-1> (75)
>    - *M* Resources/views/less/layout.less
>    <https://github.com/claroline/CoreBundle/pull/1206/files#diff-2> (17)
>
> Patch Links:
>
>    - https://github.com/claroline/CoreBundle/pull/1206.patch
>    - https://github.com/claroline/CoreBundle/pull/1206.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/CoreBundle/pull/1206>.
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by kitan1982** [comment]
+1

**Comment by arnaudbey** [comment]
:+1:

**Comment by ngodfraind** [comment]
Everyone seems to like to so now it's merged.

**Pull request merged**
