### PR TITLE
Remove dropdown login menu and remove register link in login page

### PR DESCRIPTION
**Pull request by maxailloud**
I made a pretty important change for login and register menu.
For now it's just a proposition that needs approval before being merged.

Here are the changes that this PR introduce:
 * No more dropdown menu in the right of the topbar, login link and register link is directly in the topbar
dropdown-login-register

 * No more register link in the login page
register-link-login-page

I'll tell you when to merge.

### CODE REVIEW

**Comment by clarophil** [comment]
+1

**Comment by CPAlex** [comment]
+1

**Comment by david42** [comment]
+1

**Comment by kitan1982** [comment]
+1

**Comment by LaurentGruber** [comment]
+1

**Comment by purplefish32** [comment]
+1

**Comment by ngodfraind** [comment]
Can I close this pr since the other one is merged ?

**Comment by maxailloud** [comment]
As for me you can.

**Pull request merged**
