### PR TITLE
Remove workspace access evaluator

### PR DESCRIPTION
**Pull request by stefk**
This evaluator:
- relies on a query parameter to perform a security check
- isn't fully executed anywhere
- is subject to at least three fatal errors (undefined property + 2 namespace errors)
- introduces a false sense of security [where it's used](https://github.com/claroline/AgendaBundle/commit/59b106736e0d30a8f20ea511ed34ba83db0ed960#diff-3f32d23e151c562ed946f9370292bf42R71)

### CODE REVIEW

**Comment by ngodfraind** [comment]
I'm fine with that but I'll need a way to retrieve the workspace in an listener eventually to display/handle the exception accordingly - if the workspace is not available because the start/expiration says so is different than if you're missing a role.

**Comment by stefk** [comment]
You mean the exception from `WorkspaceController#openAction` ? Because currently the only exception thrown is a 500 error ('Controller must return a response').

**Comment by ngodfraind** [comment]
Yes, it was more a test than anything else but it sort of worked before the dependency update.
Once that error is thrown it can be be used with a listener observing the kernel.exception event.
In other word, I must be able to detect there is a 403 from a workspace (and which one). From that point I can handle the error differently depending one the cause.

**Comment by stefk** [comment]
It could have worked at some point during development but the commited version, even before the update, is clearly broken (errors at lines 46, 54 and 56). Anyway, I can see the problem you're trying to solve, I just think that keeping non functional security code in the master branch is not a good idea.

**Comment by ngodfraind** [comment]
I'd rather fix it than removing it atm.

2015-05-06 16:56 GMT+02:00 stefk <notifications@github.com>:

> It could have worked at some point during development but the commited
> version, even before the update, is clearly broken (errors at lines 46, 54
> and 56). Anyway, I can see the problem you're trying to solve, I just think
> that keeping non functional security code in the master branch is not a
> good idea.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/CoreBundle/pull/1174#issuecomment-99501720>.
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by ngodfraind** [comment]
I don't understand what happened because it obv can't work the way it is.
I remember hesitating and throwing the Exception in the WorkspaceVoter but it's not even there.
I assume I screwed a commit up. It's already used at some places so it'll be easier to fix it than to removing. I'll just throw an exception if the required query parameter isn't here.

**Comment by stefk** [comment]
The workspace voter (or another dedicated voter) would indeed be a better place IMO. Nothing forces a plugin or any core controller to use this annotation, but using the security context and thus, the voter, is unavoidable. And it could even be extended to handle checks beyond the opening of tools. Anything related to workspaces (e.g. operations on resources) could have an additional "expiration" check there.

**Pull request closed without merging**
