### PR TITLE
office

### PR DESCRIPTION
**Pull request by nathanbrasseur**

### CODE REVIEW

**Comment by maxailloud** [comment]
A little explanation for what your PR does can be very useful.

And btw did you really put your [clientId and password](https://github.com/nathanbrasseur/CoreBundle/commit/4823084329f8c459884efc7298c0ff73ec9997de#diff-cdc38f0b0d93650c5a2d5c33f54abc0aR7) to office 365 in your code?

And now you need to update your PR for merging.

**Comment by ngodfraind** [comment]
It's ok, I'll work on that at one point.

2015-03-27 13:37 GMT+01:00 Maxime AILLOUD <notifications@github.com>:

> A little explanation for what your PR does can be very useful.
>
> And btw did you really put your clientId and password
> <https://github.com/nathanbrasseur/CoreBundle/commit/4823084329f8c459884efc7298c0ff73ec9997de#diff-cdc38f0b0d93650c5a2d5c33f54abc0aR7>
> to office 365 in your code?
>
> And now you need to update your PR for merging.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/CoreBundle/pull/1025#issuecomment-86928473>.
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by maxailloud** [comment]
Got it, no problem.

**Comment by ngodfraind** [comment]
There is the new plugin for this.

**Pull request closed without merging**
