### PR TITLE
Refacto log feature for installation process

### PR DESCRIPTION
**Pull request by maxailloud**
Need this PR https://github.com/claroline/InstallationBundle/pull/4 before merge.

### CODE REVIEW

**Comment by maxailloud** [comment]
When this PR will be merged we need to do the same for other bundle because it's adding BC.

**Comment by ngodfraind** [comment]
Ok, so I'll wait the "let's break everything" point before merging it.
You'll have to wait untill mid march/april.

2015-03-04 11:49 GMT+01:00 Maxime AILLOUD <notifications@github.com>:

> When this PR will be merged we need to do the same for other bundle
> because it's adding BC.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/CoreBundle/pull/1046#issuecomment-77136283>.
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by maxailloud** [comment]
Okay no problem.
It's here and it's not gonna fly away ;-)

But I made all the PR needed for the other bundle, so if your merge other bundle maintainer will just have to do the same and we'll be good.

**Comment by ngodfraind** [comment]
Great, thanks.

2015-03-04 12:37 GMT+01:00 Maxime AILLOUD <notifications@github.com>:

> Okay no problem.
> It's here and it's not gonna fly away ;-)
>
> But I made all the PR needed for the other bundle, so if your merge other
> bundle maintainer will just have to do the same and we'll be good.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/CoreBundle/pull/1046#issuecomment-77143183>.
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Pull request merged**
